application: nazokakeryoko
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*\.(png|jpg|css|js))
  static_files: \1
  upload: (.*\.(png|jpg|css|js))  

- url: /Nazo.py
  script: Nazo.py

- url: /Set.py
  script: Set.py

- url: /answer.py
  script: answer.py

- url: /set_db
  script: set_db.py